name: Test Suite and Rubocop

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Suite and Rubocop
    strategy:
      matrix:
        ruby:
          - '3.1.2'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Test Suite
      run: bundle exec rake spec
    - name: Rubocop
      run: bundle exec rake rubocop
